<section class="mb-lg-5">
    <div class="container">
        <div class="row flex-column-reverse flex-md-row ">
            <div class="col col-md-8">
                <p class="text-uppercase text-primary font-weight-medium line-height-1 d-inline-flex mb-4">
                    <span class="mr-2"><!-- Generated by IcoMoon.io -->
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 1024 1024">
                            <title></title>
                            <g id="icomoon-ignore">
                            </g>
                            <path fill="#FF1617" d="M1024 0c0 565.539-458.461 1024-1024 1024v-1024h1024z"></path>
                        </svg>
                    </span> <span>Tire suas dúvidas</span>
                </p>
                <h2 class="font-weight-semibold letter-spacing-n1 font-size-lg">Dúvidas sobre <br>a compra do seu apê? <br>A Pri te ajuda!</h2>
                <div class="accordion" id="home-faq">

                    <div class="card border-right-0 border-left-0 border-top-0 border-bottom">
                        <div class="card-header bg-white px-0 py-3" id="home-faq-heading-1">
                            <h3 class="mb-0">
                                <button class="btn btn-link btn-block d-flex text-body font-weight-medium text-left justify-content-between px-0 collapsed" type="button" data-toggle="collapse" data-target="#home-faq-collapse-1" aria-expanded="false" aria-controls="home-faq-collapse-1" onclick="exibirMensagem()">
                                    <span class="col-auto pr-2 text-primary">•</span>
                                    <span class="col"> O que é o programa "Minha Casa Minha Vida"? </span>
                                    <span class="col-auto float-right mt-1 icon-up-arrow" id="faq-arrow">
                                        <svg width="10" height="10" viewBox="0 0 10 7" fill="none" xmlns="http://www.w3.org/2000/svg">
                                            <path fill-rule="evenodd" clip-rule="evenodd" d="M9.70711 0.292893C9.31658 -0.097631 8.68342 -0.097631 8.29289 0.292893L5 3.58579L1.70711 0.292894C1.31658 -0.0976303 0.683417 -0.0976303 0.292893 0.292894C-0.0976314 0.683418 -0.0976313 1.31658 0.292894 1.70711L5 6.41421L9.70711 1.70711C10.0976 1.31658 10.0976 0.683417 9.70711 0.292893Z" fill="#FF1617"></path>
                                        </svg>
                                    </span>

                                </button>
                            </h3>
                        </div>

                        <div id="home-faq-collapse-1" class="collapse" aria-labelledby="home-faq-heading-1" data-parent="#home-faq">
                            <div class="card-body">
                                <span class="pr-2">•</span> O Minha Casa Minha Vida foi criado pelo Governo Federal para ajudar você e sua família a realizarem o maior sonho de todo brasileiro, que é ter seu próprio apê. Isso significa que você terá uma série de facilidades e um bom prazo para pagar o seu apê. Ou seja, na prática, você terá uma ajuda financeira em forma de desconto no valor do seu apê, a começar por taxas de juros bem baixinhas. Com esse programa, na Plano&amp;Plano, você vai sair do aluguel.
                            </div>
                        </div>
                    </div>

                    <div class="card border-right-0 border-left-0 border-top-0 border-bottom">
                        <div class="card-header bg-white px-0 py-3" id="home-faq-heading-2">
                            <h3 class="mb-0">
                                <button class="btn btn-link btn-block d-flex text-body font-weight-medium text-left justify-content-between px-0 collapsed" type="button" data-toggle="collapse" data-target="#home-faq-collapse-2" aria-expanded="true" aria-controls="home-faq-collapse-2" onclick="exibirMensagem()">
                                    <span class="col-auto pr-2 text-primary">•</span>
                                    <span class="col"> Quem tem direito a participar do Minha Casa Minha Vida? </span>
                                    <span class="col-auto float-right mt-1 icon-up-arrow" id="faq-arrow">
                                        <svg width="10" height="10" viewBox="0 0 10 7" fill="none" xmlns="http://www.w3.org/2000/svg">
                                            <path fill-rule="evenodd" clip-rule="evenodd" d="M9.70711 0.292893C9.31658 -0.097631 8.68342 -0.097631 8.29289 0.292893L5 3.58579L1.70711 0.292894C1.31658 -0.0976303 0.683417 -0.0976303 0.292893 0.292894C-0.0976314 0.683418 -0.0976313 1.31658 0.292894 1.70711L5 6.41421L9.70711 1.70711C10.0976 1.31658 10.0976 0.683417 9.70711 0.292893Z" fill="#FF1617"></path>
                                        </svg>
                                    </span>

                                </button>
                            </h3>
                        </div>

                        <div id="home-faq-collapse-2" class="collapse" aria-labelledby="home-faq-heading-2" data-parent="#home-faq">
                            <div class="card-body">
                                <span class="pr-2">•</span> Para se inscrever no Minha Casa Minha Vida é preciso saber que ele funciona através de faixas de renda. Isso quer dizer que você e sua família entram numa determinada faixa pelo programa, de acordo com o que vocês ganham por mês.
                            </div>
                        </div>
                    </div>

                    <div class="card border-right-0 border-left-0 border-top-0 border-bottom">
                        <div class="card-header bg-white px-0 py-3" id="home-faq-heading-3">
                            <h3 class="mb-0">
                                <button class="btn btn-link btn-block d-flex text-body font-weight-medium text-left justify-content-between px-0 collapsed" type="button" data-toggle="collapse" data-target="#home-faq-collapse-3" aria-expanded="true" aria-controls="home-faq-collapse-3" onclick="exibirMensagem()">
                                    <span class="col-auto pr-2 text-primary">•</span>
                                    <span class="col"> O que é renda familiar? </span>
                                    <span class="col-auto float-right mt-1 icon-up-arrow" id="faq-arrow">
                                        <svg width="10" height="10" viewBox="0 0 10 7" fill="none" xmlns="http://www.w3.org/2000/svg">
                                            <path fill-rule="evenodd" clip-rule="evenodd" d="M9.70711 0.292893C9.31658 -0.097631 8.68342 -0.097631 8.29289 0.292893L5 3.58579L1.70711 0.292894C1.31658 -0.0976303 0.683417 -0.0976303 0.292893 0.292894C-0.0976314 0.683418 -0.0976313 1.31658 0.292894 1.70711L5 6.41421L9.70711 1.70711C10.0976 1.31658 10.0976 0.683417 9.70711 0.292893Z" fill="#FF1617"></path>
                                        </svg>
                                    </span>

                                </button>
                            </h3>
                        </div>

                        <div id="home-faq-collapse-3" class="collapse" aria-labelledby="home-faq-heading-3" data-parent="#home-faq">
                            <div class="card-body">
                                <span class="pr-2">•</span> Uma renda familiar é composta pela renda de até três pessoas que moram juntas, tendo laços de sangue ou não. Você pode somar a sua renda com até mais duas pessoas que morem com você. Somando todo esse valor você saberá qual é a sua renda familiar mensal.
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col mt-4 p-0">
                    <a href="/faq" title="Veja mais duvidas" class="text-primary text-uppercase font-size-md font-weight-bold">Veja mais dúvidas</a>
                </div>
            </div>
            <div class="col col-md-4">
                <picture class="">
                    <source type="image/webp" srcset="/assets/img/priscila-duvidas.webp" loading="lazy">
                    <source type="image/png" srcset="/assets/img/priscila-duvidas.png" loading="lazy"> <img class="img-fluid" src="/assets/img/priscila-duvidas.png" alt="FAQ" loading="lazy">
                </picture>
            </div>
        </div>
    </div>
</section>